
pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'python tests/test_login.py'
                sh 'python validation/data_validation.py'
            }
        }
    }
}
